name: 🐛 Bug Report
description: Create a report to help us improve
labels: ["⚠️bug?"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting!
        First, in order to avoid duplicate Issues, please search to see if the problem you found has already been reported on [misskey.niri.la issues](https://github.com/niri-la/misskey.niri.la/issues).
        Also, you should report issues only when reproduced on `misskey.niri.la`.

  - type: textarea
    attributes:
      label: 💡 Summary
      description: Tell us what the bug is
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🥰 Expected Behavior
      description: Tell us what should happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🤬 Actual Behavior
      description: |
        Tell us what happens instead of the expected behavior.
        Please include errors from the developer console and/or server log files if you have access to them.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 Steps to Reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 💻 Frontend Environment
      description: |
        Tell us where on the platform it happens
        DO NOT WRITE "latest". Please provide the specific version.

        Examples:
          * Model and OS of the device(s): MacBook Pro (14inch, 2021), macOS Ventura 13.4
          * Browser: Chrome 113.0.5672.126
      value: |
        * Model and OS of the device(s):
        * Browser:
      render: markdown
    validations:
      required: false
